[package]
name = "soluna"
version = "0.0.0"
edition = "2021"
description = "Personal library reserved for future use."
readme = "README.md"
repository = "https://github.com/Soluna7/soluna"
license-file = "LICENSE"


[dependencies]
